## Phase 2 - Numpy Array Operations

In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing", arr[2:7])
print("with Step", arr[1:8:2])
print("Begative indexing: ", arr[-3])

Basic Slicing [3 4 5 6 7]
with Step [2 4 6 8]
Begative indexing:  7


In [8]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific element", arr_2d[1,2])
print("Entir row: ", arr_2d[1])
print("Entire Column", arr_2d[:,1])

Specific element 6
Entir row:  [4 5 6]
Entire Column [2 5 8]


### Sorting

In [13]:
unsorted = np.array([2,3,1,5,4,8,7])
print("Sorted array: ",np.sort(unsorted))

arr_2d_Unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by column\n", np.sort(arr_2d_Unsorted, axis=1))

Sorted array:  [1 2 3 4 5 7 8]
Sorted 2D array by column
 [[1 3]
 [1 2]
 [2 3]]


### Filtering

In [14]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


### Filter with mask

what is mask? conditon which is satisfied

In [15]:
mask = numbers > 5
print("Numbers greator than 5 ", numbers[mask])

Numbers greator than 5  [ 6  7  8  9 10]


### Fancing Indexing

In [17]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("Np where", numbers[where_result])

[1 3 5]
Np where [ 6  7  8  9 10]


This is like

if(numbers > 5):
    numbers * 4
else:
    numbers

In [20]:
condition_array = np.where(numbers > 5, numbers * 1, numbers)
print(condition_array)

[ 1  2  3  4  5  6  7  8  9 10]


### Adding and removing Data

In [21]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


#### array commpatibility

In [22]:
a = np.array([1,2,3])
b = np.array([4.5,6])
c = np.array([7,8,9])

print("Compatibility shapes", a.shape == b.shape)


Compatibility shapes False


In [29]:
orignal = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
print(orignal)
print(new_row)

with_new_row = np.vstack((orignal,new_row))

print("\n",with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((orignal,new_col))

print("\n", with_new_col)

[[1 2]
 [3 4]]
[[5 6]]

 [[1 2]
 [3 4]
 [5 6]]

 [[1 2 7]
 [3 4 8]]


In [30]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4 5]
