In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1D array:",arr_1d)

1D array: [1 2 3 4 5]


In [3]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array:",arr_2d)

2D array: [[1 2 3]
 [4 5 6]]


### List vs Numpy

In [5]:
py_list = [1,2,3]
print("Python List multiplication:",py_list * 2)
arr_3 = np.array([1,2,3]) # element wise multiplication
print("3D array:",arr_3*2)

Python List multiplication: [1, 2, 3, 1, 2, 3]
3D array: [2 4 6]


In [7]:
import time
start = time.time()
py_list = [i*2 for i in range(10000000)]

print("\n List oOperation time: ", time.time() - start)

arr = np.arange(1000000) * 2
print("\n numpy oOperation time: ", time.time() - start)


 List oOperation time:  1.717637538909912

 numpy oOperation time:  1.7270817756652832


### creating array from start

In [9]:
zeros = np.zeros((3,4))
print("Zeros array: \n", zeros)

ones = np.ones((2,3))
print("Ones array", ones)

full = np.full((2,2),7)
print("full array: \n", full)

random = np.random.random((2,3))
print("Randam Array: \n", random)

sequence = np.arange(0,10,2)
print("Sequence Array: \n", sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
Randam Array: 
 [[0.555473   0.15528846 0.5320624 ]
 [0.67104836 0.64849177 0.08788136]]
Sequence Array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [10]:
vector = np.array([1,2,3])
print("Vector: ", vector)

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor:  [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


### Array Properties

In [12]:
arr = np.array([[1,2,3],[4,5,6]])

print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Dtype: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
Dtype:  int64


### Array Reshaping

In [17]:
arr = np.arange(12)
print("Orignal: ", arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array ", reshaped)

flattened = arr.flatten()
print("\n Flattened array ", flattened)

#ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

#Transpose

transpose = reshaped.T
print("Transepose: ", transpose)

Orignal:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transepose:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
