In [12]:
import numpy as np
import pandas as pd

In [13]:
df = pd.read_csv('customer.csv')

In [14]:
df.sample(5)

,age,gender,review,education,purchased
8,65,Female,Average,UG,No
20,57,Female,Average,School,Yes
46,64,Female,Poor,PG,No
33,89,Female,Good,PG,Yes
22,18,Female,Poor,PG,Yes


In [15]:
df = df.iloc[:,2:]

In [16]:
df.head()

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns="purchased"), df["purchased"], test_size = 0.2, random_state = 0)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((40, 2), (10, 2), (40,), (10,))

In [18]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
X_train = oe.fit_transform(X_train)
X_test = oe.transform(X_test)


In [19]:
X_train

array([[1., 0.],
       [2., 1.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [2., 1.],
       [2., 0.],
       [2., 0.],
       [1., 2.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 2.],
       [0., 0.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 2.]])

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df.drop(columns="purchased"), df["purchased"], test_size=0.2, random_state=0
)

from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average','Good'], ['School','UG','PG']])
X_train = oe.fit_transform(X_train)   # fit ONLY on original text data
X_test = oe.transform(X_test)

In [38]:
oe.categories_

[]

In [31]:
X_train

array([[2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [32]:
from sklearn.preprocessing import LabelEncoder

In [33]:
le = LabelEncoder()

In [34]:
le.fit(y_train)

LabelEncoder()

In [35]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [36]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [37]:
y_train

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])