<a href="https://colab.research.google.com/github/hasnainaliasghar/ai-journey/blob/main/08%20Pytorch/Tensors%20Basic/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cpu
False


# Creating Tensors

In [4]:
# using Empty
a = torch.empty(2,3)

In [5]:
#check type
type(a)

torch.Tensor

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.rand(2,3)

tensor([[0.2867, 0.5184, 0.6409],
        [0.6879, 0.0400, 0.1494]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
#other ways

#arange
torch.arange(0,18,2).reshape(3,3)

#Linspace
torch.linspace(0,18,12).reshape(3,4)

#Logspace
torch.logspace(-9,10,15)

tensor([1.0000e-09, 2.2758e-08, 5.1795e-07, 1.1788e-05, 2.6827e-04, 6.1054e-03,
        1.3895e-01, 3.1623e+00, 7.1969e+01, 1.6379e+03, 3.7276e+04, 8.4834e+05,
        1.9307e+07, 4.3940e+08, 1.0000e+10])

# Tensors Shape

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[   711267551,            0, 476741369972],
        [425201762418, 197568495720, 489626271860]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [26]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

# Datatypes

In [20]:
x.dtype

torch.int64

In [21]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [22]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [25]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

# Scalar Operations

In [31]:
x = torch.rand(2,2)
x

tensor([[0.5277, 0.2472],
        [0.7909, 0.4235]])

In [32]:
#addition
x + 2
x*2
x-2
x/2

tensor([[0.2638, 0.1236],
        [0.3954, 0.2117]])

In [33]:
c = torch.tensor([1,-2,3,-4])

In [34]:
torch.neg(c)

tensor([-1,  2, -3,  4])