<a href="https://colab.research.google.com/github/hasnainaliasghar/ai-journey/blob/main/08%20Pytorch/Tensors%20Basic/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cpu
False


# Creating Tensors

In [55]:
# using Empty
a = torch.empty(2,3)

In [56]:
#check type
type(a)

torch.Tensor

In [57]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [58]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [59]:
torch.rand(2,3)

tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]])

In [60]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [61]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [62]:
#other ways

#arange
torch.arange(0,18,2).reshape(3,3)

#Linspace
torch.linspace(0,18,12).reshape(3,4)

#Logspace
torch.logspace(-9,10,15)

tensor([1.0000e-09, 2.2758e-08, 5.1795e-07, 1.1788e-05, 2.6827e-04, 6.1054e-03,
        1.3895e-01, 3.1623e+00, 7.1969e+01, 1.6379e+03, 3.7276e+04, 8.4834e+05,
        1.9307e+07, 4.3940e+08, 1.0000e+10])

# Tensors Shape

In [63]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [64]:
torch.empty_like(x)

tensor([[   727491261,            0, 489626271744],
        [          65,    728791504,    723009088]])

In [65]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [66]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [67]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

# Datatypes

In [68]:
x.dtype

torch.int64

In [69]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [70]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [71]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

# Scalar Operations

In [72]:
x = torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [73]:
#addition
x + 2
x*2
x-2
x/2

tensor([[0.1119, 0.1512],
        [0.0892, 0.4119]])

In [74]:
c = torch.tensor([1,-2,3,-4])

In [75]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [76]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [77]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [78]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [79]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [80]:
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# Reduction operation

In [81]:
e = torch.randint(size=(2,2), low =0 , high=10)
e

tensor([[4, 6],
        [0, 1]])

In [82]:
torch.mean(e, dtype=torch.float64)

tensor(2.7500, dtype=torch.float64)

In [83]:
torch.var(e.to(torch.float64))

tensor(7.5833, dtype=torch.float64)

In [84]:
torch.argmin(e)

tensor(2)

# Matrix Operation

In [85]:
torch.mul(e,e)

tensor([[16, 36],
        [ 0,  1]])

In [87]:
#determinant
torch.det(e.float())

tensor(4.)

# Copying a tensor

In [89]:
a = torch.rand(2,3)

In [90]:
b = a

In [91]:
b

tensor([[0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])

In [92]:
a[0][0] = 0

In [93]:
a

tensor([[0.0000, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])

In [94]:
b

tensor([[0.0000, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])

In [95]:
id(a)

137498705942384

In [96]:
id(b)

137498705942384

In [97]:
b = a.clone()

In [98]:
a

tensor([[0.0000, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])

In [99]:
b

tensor([[0.0000, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])

In [100]:
a[0][0] = 10

In [101]:
a

tensor([[10.0000,  0.4892,  0.2426],
        [ 0.7003,  0.5277,  0.2472]])

In [102]:
b

tensor([[0.0000, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])

In [103]:
id(a)

137498705942384

In [104]:
id(b)

137498643763184

# Tensor Operations on GPU

In [3]:
import torch
import time

In [4]:
torch.cuda.is_available()

True

In [5]:
device = torch.device('cuda')

In [6]:
# creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3464, 0.0560, 0.2957],
        [0.0455, 0.1983, 0.4234]], device='cuda:0')

In [7]:
a = torch.rand(2,3)

In [8]:
a

tensor([[0.0675, 0.4097, 0.1585],
        [0.2481, 0.6590, 0.6386]])

In [10]:
b = a.to(device)

In [11]:
b + 5

tensor([[5.0675, 5.4097, 5.1585],
        [5.2481, 5.6590, 5.6386]], device='cuda:0')

In [12]:
size = 10000
matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"CPU time: {cpu_time: .4f} seconds")

#Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

start_time = time.time()
result_cpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(f"GPU time: {gpu_time: .4f} seconds")

print("\n Speedup(Cpu/gpu): ", cpu_time/gpu_time)

CPU time:  17.7417 seconds
GPU time:  0.6891 seconds

 Speedup(Cpu/gpu):  25.74678425802746


## Resphaping Tensors

In [14]:
a = torch.ones(4,4)
a = a.to('cuda')


In [15]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]], device='cuda:0')

In [16]:
#flatter
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       device='cuda:0')

In [18]:
b = torch.rand(2,3,4)
b

tensor([[[0.4600, 0.3160, 0.4794, 0.9425],
         [0.1312, 0.6040, 0.0102, 0.3808],
         [0.2923, 0.9092, 0.5570, 0.2801]],

        [[0.8201, 0.1363, 0.5657, 0.4211],
         [0.7747, 0.7004, 0.5238, 0.7342],
         [0.1627, 0.3302, 0.0743, 0.1767]]])

In [20]:
b. permute(2,1,0).shape

torch.Size([4, 3, 2])

In [26]:
c = torch.rand(226,226,3)
c.unsqueeze(dim=0).shape

torch.Size([1, 226, 226, 3])

In [27]:
d = torch.rand(1,20)

In [29]:
d.squeeze(dim=0).shape

torch.Size([20])

# Numpy vs Pytorch

In [30]:
import numpy as np

In [32]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [33]:
b = a.numpy()

In [35]:
type(b)

numpy.ndarray

In [36]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [37]:
torch.from_numpy(c)

tensor([1, 2, 3])