<a href="https://colab.research.google.com/github/hasnainaliasghar/ai-journey/blob/main/08%20Pytorch/Tensors%20Basic/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cpu
False


# Creating Tensors

In [55]:
# using Empty
a = torch.empty(2,3)

In [56]:
#check type
type(a)

torch.Tensor

In [57]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [58]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [59]:
torch.rand(2,3)

tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]])

In [60]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [61]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [62]:
#other ways

#arange
torch.arange(0,18,2).reshape(3,3)

#Linspace
torch.linspace(0,18,12).reshape(3,4)

#Logspace
torch.logspace(-9,10,15)

tensor([1.0000e-09, 2.2758e-08, 5.1795e-07, 1.1788e-05, 2.6827e-04, 6.1054e-03,
        1.3895e-01, 3.1623e+00, 7.1969e+01, 1.6379e+03, 3.7276e+04, 8.4834e+05,
        1.9307e+07, 4.3940e+08, 1.0000e+10])

# Tensors Shape

In [63]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [64]:
torch.empty_like(x)

tensor([[   727491261,            0, 489626271744],
        [          65,    728791504,    723009088]])

In [65]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [66]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [67]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

# Datatypes

In [68]:
x.dtype

torch.int64

In [69]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [70]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [71]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

# Scalar Operations

In [72]:
x = torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [73]:
#addition
x + 2
x*2
x-2
x/2

tensor([[0.1119, 0.1512],
        [0.0892, 0.4119]])

In [74]:
c = torch.tensor([1,-2,3,-4])

In [75]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [76]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [77]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [78]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [79]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [80]:
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# Reduction operation

In [81]:
e = torch.randint(size=(2,2), low =0 , high=10)
e

tensor([[4, 6],
        [0, 1]])

In [82]:
torch.mean(e, dtype=torch.float64)

tensor(2.7500, dtype=torch.float64)

In [83]:
torch.var(e.to(torch.float64))

tensor(7.5833, dtype=torch.float64)

In [84]:
torch.argmin(e)

tensor(2)

# Matrix Operation

In [85]:
torch.mul(e,e)

tensor([[16, 36],
        [ 0,  1]])

In [87]:
#determinant
torch.det(e.float())

tensor(4.)