In [9]:
import pickle
import numpy as np
import pandas as pd

In [10]:
pipe = pickle.load(open('pipe.pkl', 'rb'))

In [29]:
test_input2 = pd.DataFrame(
    [[2, 'male', 31.0, 0, 0, 10.5, 'S']],
    columns=['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
)

In [30]:
pipe.predict(test_input2)

array([1])

In [41]:
test_input3 = pd.DataFrame(
    [[2, 'male', 31.0, 0, 0, 10.5, 'S']],
    columns=['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
)

In [42]:
pipe.predict(test_input3)

array([1])

In [43]:
p1 = pd.DataFrame([[1, 'female', 24.0, 0, 0, 100.0, 'C']], columns=['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked'])

# Person 2: old poor man, 3rd class
p2 = pd.DataFrame([[3, 'male', 60.0, 0, 0, 7.5, 'S']], columns=['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked'])

# Person 3: child with family
p3 = pd.DataFrame([[2, 'female', 8.0, 1, 2, 25.0, 'Q']], columns=['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked'])

print(pipe.predict(p1))
print(pipe.predict(p2))
print(pipe.predict(p3))

[1]
[0]
[1]


In [47]:
young = pd.DataFrame(
    [[1, 'female', 12.0, 4, 0, 100.0, 'S']], columns=['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']
)

In [48]:
pipe.predict(young)

array([1])